Light.path                  =   [Light.start_position2      ;...
                                 Light.reflection_position];
Light.path2                 =   [Light.reflection_position  ;...
                                (Light.reflection_position  +...
                                 Light.reflection_vector*20)];
plot3([Light.path(:,1)],...
      [Light.path(:,2)],...
      [Light.path(:,3)],'yellow-x')
plot3([Light.path2(:,1)],...
      [Light.path2(:,2)],...
      [Light.path2(:,3)],'yellow--x')
drawnow

for j==n_j(k)
    set (gcf,'Visible','on')
    drawnow
    figure(1)
    keyboard
end
    