
light_path                  =   [light_start_position2      ;...
                                 light_reflection_position];
light_path2                 =   [light_reflection_position  ;...
                                (light_reflection_position  +...
                                 light_reflection_vector*20)];
plot3([light_path(:,1)],...
      [light_path(:,2)],...
      [light_path(:,3)],'black-x')
plot3([light_path2(:,1)],...
      [light_path2(:,2)],...
      [light_path2(:,3)],'yellow--x')
% plot3([light_path2(:,1)],...
%       [light_path2(:,2)],...
%       [light_path2(:,3)],'rs',...
%       'MarkerSize',10,...
%       'MarkerFaceColor','r')  
drawnow
figure(1)